export const users = [
    { id: '00001', name: 'Christine Brooks', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Waiting for approval' },
    { id: '00002', name: 'Rosie Pearson', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00003', name: 'Darrell Caldwell', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00004', name: 'Gilbert Johnston', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00005', name: 'Alan Cam', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00006', name: 'Jayvay Eei', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Waiting for approval' },
    { id: '00007', name: 'Karen Lee', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Waiting for approval' },
    { id: '00008', name: 'Michael Johnson', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00009', name: 'Sarah Davis', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00010', name: 'David Lee', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00011', name: 'Emily Thompson', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00012', name: 'James Wilson', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00013', name: 'Isabella Johnson', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Waiting for approval' },
    { id: '00014', name: 'Ethan Williams', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00015', name: 'Sophia Brown', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00016', name: 'Jack Taylor', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00017', name: 'Olivia Martinez', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00018', name: 'Noah Miller', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00019', name: 'Ava Davis', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00020', name: 'William Garcia', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00021', name: 'Mia Rodriguez', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00022', name: 'Lucas Wilson', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00023', name: 'Amelia Smith', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Waiting for approval' },
    { id: '00024', name: 'Mason Martinez', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00025', name: 'Charlotte Lee', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00026', name: 'Oliver Gonzalez', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00027', name: 'Evelyn Perez', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00028', name: 'Jacob Brown', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00029', name: 'Emma Martinez', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Approved' },
    { id: '00030', name: 'Logan Johnson', package: 'CosmeSticSurgey', doctor: 'Dr. Adisak Intana', status: 'Waiting for approval' }
  ];